config/routes.rb
Rails.application.routes.draw do
  resources :departments

  resources :statuses

  resources :prospects, except: [:new, :create] do
    get "archive", on: :collection
  end

  get 'prospects/index'

  devise_for :users

  root 'prospects#index'

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :prospects
  has_many :users
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :prospect

  def self.receive_mail(message)
    email = Email.create name: message[:from].value.split(" <").first, address: message.from.first, subject: message.subject, body: message.body.decoded

    email.attach_to_prospect
  end

  def attach_to_prospect
    prospect = Prospect.find_or_create_by(email: address)
    new_status = Status.find_by_name("New")
    prospect.update(name: name, status: new_status)
    self.prospect = prospect
    self.save
  end
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  has_many :emails
  belongs_to :department
  belongs_to :status

  def self.archive
    self.includes(:status).where(statuses: { name: ["Declined", "Hired"]} )
  end

  def self.active
    Prospect.includes(:status).where.not(statuses: { name: ["Declined", "Hired"]} )
  end

end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :prospects
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable :registerable, and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_department, only: [:edit, :update, :destroy, :show]

  def index
    @departments = Department.all
    @department = Department.new
  end

  def show
    # @department = Department.find(params[:id])
    @prospects = @department.prospects
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    @department.save
    redirect_to departments_path, notice: 'Department was successfully created'
  end

  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params[:department].permit(:name, :manager)
    end

end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.active
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/1/edit
  def edit
  end

  def archive
    @prospects = Prospect.archive
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: 'Prospect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params[:prospect].permit(:department_id, :status_id, :notes)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status, only: [:edit, :update, :destroy]

  def index
    @statuses = Status.all
    @status = Status.new
  end

  def show
  end

  # GET /statuses/1/edit
  def edit
  end

  def create
    @status = Status.new(status_params)
    @status.save
    redirect_to statuses_path, notice: 'Status was successfully created'
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params[:status].permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/departments/index.html.slim
div class="large-10 large-offset-4 columns"
  H1 Departments

  table
    thead
      tr
        th Departments
        th Manager

    tbody
      - @departments.each do |department|
        tr
          td = link_to department.name, department
          td = department.manager
          td = link_to 'Destroy', department, data: {:confirm => 'Are you sure?'}, :method => :delete
    = simple_form_for @department do |f|
      td = f.input :name, label: 'New Department Name:'
      td = f.input :manager, label: 'Department Manager:'
      td = f.button :submit, 'Add Department'

app/views/departments/show.html.slim
div class="large-10 large-offset-2 columns"
  H1 Prospects for #{@department.name}

  = render 'shared/dashboard'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/prospects">Prospect Tracker</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right menu">
      <% if current_user %>
        <li class="menu-item"><%= link_to current_user.department.name, department_path(current_user.department) %></li>
        <li class="has-dropdown">
          <a href="#">More</a>
          <ul class="dropdown">
            <li class="menu-item"><%= link_to 'All Departments', departments_path %></li>
            <li class="menu-item"><%= link_to 'Statuses', statuses_path %></li>
            <li class="menu-item"><%= link_to 'Archive', archive_prospects_path %></li>
          </ul>
        </li>
        <li class="menu-item"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="menu-item"><%= link_to 'Login', new_user_session_path %> </li>
      <% end %>
    </ul>
  </section>
</nav>

    <%= yield %>

  </body>
</html>

app/views/prospects/_form.html.slim
= form_for @prospect do |f|
  - if @prospect.errors.any?
    #error_explanation
      h2 = "#{pluralize(@prospect.errors.count, "error")} prohibited this prospect from being saved:"
      ul
        - @prospect.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/prospects/archive.html.slim
div class="large-10 large-offset-2 columns"
  h1 Company Archived Prospects

  = render 'shared/dashboard'

app/views/prospects/edit.html.slim
h1 Editing prospect

== render 'form'

= link_to 'Show', @prospect
'|
= link_to 'Back', prospects_path

app/views/prospects/index.html.slim
div class="large-10 large-offset-2 columns"
  h1 Company Active Prospects

  = render 'shared/dashboard'

app/views/prospects/new.html.slim
h1 New prospect

== render 'form'

= link_to 'Back', prospects_path

app/views/prospects/show.html.slim
p#notice = notice

= link_to 'Back', prospects_path

div class="small-3 columns"
  = simple_form_for @prospect do |f|
    = f.association :status, prompt: "Current Status", label: false
    = f.association :department, prompt: "Select a Department", label: false
    = f.input :notes, label: 'Notes for Prospect:'
    = f.button :submit, 'Update Note'

div class="small-8 columns"

  h3
    ' Prospect:
    = @prospect.name
  h4
    ' Email:
    = @prospect.email
  h4
    ' Department:
    = @prospect.department.try(:name)

  - @prospect.emails.each do |email|
    div class="panel"
      p
        ' SUBJECT
        br
        = email.subject
      p
        ' EMAIL
        br
        = email.body
  br

app/views/shared/_dashboard.html.slim
table
  thead
    tr
      th Name
      th Email
      th Status
      th Department

  tbody
    tr
    - @prospects.each do |prospect|
      tr
      = simple_form_for prospect do |f|
        td = prospect.name
        td = prospect.email
        td = f.association :status, prompt: "Current Status", label: false
        td = f.association :department, prompt: "Select Department", label: false
        td = f.button :submit
        td = link_to 'Show', prospect
        td = link_to 'Edit', edit_prospect_path(prospect)
        td = link_to 'Destroy', prospect, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/statuses/index.html.slim
div class="large-10 large-offset-4 columns"
  H1 All Statuses for Prospects

  table
    thead
      tr
        th Status

    tbody
      - @statuses.each do |status|
        tr
          td = status.name
          td = link_to 'Destroy', status, data: {:confirm => 'Are you sure?'}, :method => :delete
    = simple_form_for @status do |f|
      td = f.input :name, label: 'New Status for Prospects:'
      td = f.button :submit, 'Add Status'